#!/bin/bash -xe
# set up kafka configuration of server.properties

bench_dir=/opt/scriptKafka
prd_temp_file=$bench_dir/producer.properties
brk_f=$bench_dir/brk.conf
prd_f=$bench_dir/cons.conf
prd_dest_file=/home/tushar/kafka_2.11-1.0.0/config/

# creating broker_list below:
brk_list=""
[ ! -f $brk_f ] && { echo "$brk_f file not found"; exit 1; }

i=0
while read f
do
  b_uri=$f:9092
  b_uri_1=$f:9093
  b_uri_2=$f:9094
  if [ $i -eq "0" ]
     then
          brk_list="$b_uri, $b_uri_1, $b_uri_2"
     else
          brk_list="$brk_list,$b_uri, $b_uri_1, $b_uri_2"
  fi
  i=$(( i + 1 ))
done < $brk_f

pushd $bench_dir

##configuring consumer.properties
sed -i "s/^bootstrap.servers/#bootstrap.servers/" $prd_temp_file
echo "bootstrap.servers=$brk_list" >> $prd_temp_file

prd_list=""
[ ! -f $prd_f ] && { echo "$prd_f file not found"; exit 1; }

while read f
do
  prd_list="$prd_list $f"
done < $prd_f

for prd in $prd_list
do
  echo $prd
  scp $prd_temp_file tushar@prd:$prd_dest_file
done
