#!/bin/bash -xe
source_dir=/root
kpath=/root/kafka_2.11-1.0.0/bin
prog_STRING=kafka-console-producer.sh
file_STRING=test15
bk_list=brk-3:9092
TOPIC_NAME=$1
#host=prd-1
zk=zk-1:2181,zk-3:2181,zk-4:2181/kafka

#ssh root@prd-1 $kpath/$prog_STRING --broker-list $bk_list --topic $TOPIC_NAME < $source_dir/$file_STRING &
ssh root@prd-1 "$kpath/$prog_STRING --broker-list $bk_list --topic $TOPIC_NAME "
