#!/bin/bash -xe
nfs_dir=/nfs/software
kafka_pkg=kafka_2.11-1.0.0
kafka_pkg_tgz=${kafka_pkg}.tgz
#need to ensure that nfs/bin/kbench consists of:
#    -zookeeper.conf
#    -prd.conf
#    -broker.conf
#    -cons.conf

pushd /opt
rm -rf /opt/kafka*
tar xzvf $nfs_dir/$kafka_pkg_tgz
ln -s ${kafka_pkg} kafka

mkdir -p /opt/kafka/kbench
cp -r /nfs/bin/kbench/* /opt/kafka/kbench
