#!/bin/bash -xe
#pushd /opt
#rm -rf /opt/scriptKafka*
#mkdir -p /opt/scriptKafka
#pushd /opt/scriptKafka
wget http://mirror.reverse.net/pub/apache/kafka/1.0.0/kafka_2.11-1.0.0.tgz
tar xzvf kafka_2.11-1.0.0.tgz
#ln -s ${kafka_pkg} kafka

#mkdir -p /opt/kafka/kbench
#cp -r /nfs/bin/kbench/* /opt/kafka/kbench

#wget http://mirror.reverse.net/pub/apache/kafka/1.0.0/kafka_2.11-1.0.0.tgz
#tar-zxvf kafka_2.11-1.0.0.tgz
