#!/bin/bash -xe
bench_dir=/opt/scriptKafka
cons_temp_file=$bench_dir/consumer.properties
brk_f=$bench_dir/brk.conf
cons_f=$bench_dir/cons.conf
cons_dest_file=/root/kafka_2.11-1.0.0/config/

# creating broker_list below:
brk_list=""
[ ! -f $brk_f ] && { echo "$brk_f file not found"; exit 1; }

i=0
while read f
do
  b_uri=$f:9092
  b_uri_1=$f:9093
  b_uri_2=$f:9094
  if [ $i -eq "0" ]
     then
          brk_list="$b_uri, $b_uri_1, $b_uri_2"
     else
          brk_list="$brk_list,$b_uri, $b_uri_1, $b_uri_2"
  fi
  i=$(( i + 1 ))
done < $brk_f

pushd $bench_dir

#configuring consumer.properties.
configComment(){
  sed -i "s/^\([^#]\)/#\1/g" $cons_temp_file
  sed -i "s/^bootstrap.servers/#bootstrap.servers/" $cons_temp_file
}

#updating consumer.properties.
configUpdate(){
  echo "bootstrap.servers=$brk_list" >> $cons_temp_file
  echo "group.id=test-consumer-group" >> $cons_temp_file
}

cons_list=""
[ ! -f $cons_f ] && { echo "$cons_f file not found"; exit 1; }

while read f
do
  cons_list="$cons_list $f"
done < $cons_f

#copy config consumer.properties to all consumers.
configCopy(){
  for cons in $cons_list
  do
    echo $cons
    scp $cons_temp_file root@$cons:$cons_dest_file
  done
}

#calling methods in sequence.
configComment
configUpdate
configCopy
