#!/bin/bash -xe
bench_dir=/opt/kafka/kbench
cons_f=$bench_dir/cons.conf
bin_dir=/home/tushar/kafka_2.11-1.0.0/bin
config_dir=/home/tushar/kafka_2.11-1.0.0/config
KAFKA_CONSUMER_HOME=/home/tushar/KafkaXenonConsumer
TOPIC_NAME=$@

pushd $bench_dir

cons_list=""
[ ! -f $cons_f ] && { echo "$cons_f file not found"; exit 1; }

while read f
do
  cons_list="$cons_list $f"
done < $cons_f

#installing XenonClient jar and pom in local maven repository.
for cons in cons_list
do
    ssh tushar@cons:"
    pushd $KAFKA_CONSUMER_HOME;
    mvn exec:java -Dexec.mainClass=com.levyx.kafkaConsumer.SingleConsumerMain1 -Dexec.args=$TOPIC_NAME"
done
