#!/bin/bash -xe
bench_dir=/opt/scriptKafka
zoo_f=$bench_dir/zoo.conf
pushd $bench_dir

zoo_list=""
[ ! -f $zoo_f ] && { echo "$zoo_f file not found"; exit 1; }

while read f
do
  zoo_list="$zoo_list $f"
done < $zoo_f

for zoo in $zoo_list
do
    ssh root@$zoo "rm -rf /root/kafka_2.11-1.0.0"
    scp -r kafka_2.11-1.0.0 root@$zoo:/root
done
