#!/bin/bash -xe
bench_dir=/opt/scriptKafka
zoo_file=zookeeper.properties
zoo_f=$bench_dir/zoo.conf
pushd $bench_dir

zoo_list=""
[ ! -f $zoo_f ] && { echo "$zoo_f file not found"; exit 1; }

while read f
do
  zoo_list="$zoo_list $f"
done < $zoo_f

#mounting on VMs zk-1,zk-3 and zk-4

i=1
for zoo in $zoo_list
do
  echo $zoo
  ssh root@$zoo "
  lsblk;
  umount /dev/vdb;
  umount /dev/vdc;
  rm -rf /mnt/* ;
  mkdir /mnt/nvme;
  mkdir /mnt/nvme/tmp;
  mkdir /mnt/nvme/tmp-1;
  mkfs.xfs -f /dev/vdb;
  mkfs.xfs -f /dev/vdc;
  mount /dev/vdb /mnt/nvme/tmp;
  mkdir /mnt/nvme/tmp/zookeeper;
  echo $i >> /mnt/nvme/tmp/zookeeper/myid;
  mount /dev/vdc /mnt/nvme/tmp-1;"
  i=$((i+1))
done
