#!/bin/bash -xe
bench_dir=/opt/scriptKafka
brk_f=$bench_dir/brk.conf
pushd $bench_dir

brk_list=""
[ ! -f $brk_f ] && { echo "$brk_f file not found"; exit 1; }

while read f
do
  brk_list="$brk_list $f"
done < $brk_f


for brk in $brk_list
do
  echo $brk
  ssh root@$brk "
  lsblk;
  umount /dev/vdb;
  rm -rf /root/logs;
  mkdir /root/logs;
  mkfs.xfs -f /dev/vdb;
  mount /dev/vdb /root/logs;
  "
done
