#!/bin/bash -xe
bench_dir=/opt/kafka/kbench
brk_f=$bench_dir/brk.conf
bin_dir=/home/tushar/kafka_2.11-1.0.0/bin
config_dir=/home/tushar/kafka_2.11-1.0.0/config
pushd $bench_dir

brk_list=""
[ ! -f $brk_f ] && { echo "$brk_f file not found"; exit 1; }

while read f
do
  brk_list="$brk_list $f"
done < $brk_f

for brk in $brk_list
do
    echo $brk
    ssh tushar@$brk $bin_dir/kafka-server-start.sh $config_dir/server.properties &
    ssh tushar@$brk $bin_dir/kafka-server-start.sh $config_dir/server-1.properties &
    ssh tushar@$brk $bin_dir/kafka-server-start.sh $config_dir/server-2.properties &
done
